### PR TITLE
Removes invalid commas

### PR DESCRIPTION
**Pull request by burner**

### CODE REVIEW

**Comment by workhorsy** [comment]
Interesting. I hadn't noticed this before. I had started writing my dub.json files in JSON5 instead of JSON. Is there any documentation on what we should use in D?

**Comment by burner** [comment]
Nothing definitive I could point to. IMHO dub.json should be readable by std.json.
Removing the comma's creates that state.

**Comment by workhorsy** [comment]
Thanks

**Comment by burner** [comment]
thanks for merging

**Pull request merged**
